compute_leverage <- function(object, ensemble_idx = 1) {
  if (is.list(object$psi_a)) {
    psi_a_j <- object$psi_a[[min(ensemble_idx, length(object$psi_a))]]
    J_j <- object$J[[min(ensemble_idx, length(object$J))]]
    J_inv <- solve(J_j)
    J_inv_vec <- as.vector(t(J_inv))
    
    p <- ncol(J_j)
    n <- object$nobs
    dim(psi_a_j) <- c(n, p * p)
    h <- (psi_a_j %*% J_inv_vec) / n
    return(as.vector(h))
  } else if (!is.null(object$psi_a) && is.matrix(object$psi_a)) {
    psi_a_j <- object$psi_a[,
      min(ensemble_idx, ncol(object$psi_a))]
    J_j <- as.numeric(object$J[[min(ensemble_idx, length(object$J))]])
    return(as.vector(psi_a_j / (object$nobs * J_j)))
  }#IFELSE

  # Fallback for gracefully handling objects generated by older package versions
  fit_obj <- if (!is.null(object$ols_fit)) {
    object$ols_fit
  } else {
    object$iv_fit
  }#IFELSE
  if (is.list(fit_obj) &&
      !inherits(fit_obj, "lm") &&
      !inherits(fit_obj, "ivreg")) {
    fit_obj <- fit_obj[[ensemble_idx]]
  }#IF
  as.vector(stats::hatvalues(fit_obj))
}#COMPUTE_LEVERAGE

compute_ddml_variance <- function(scores, J,
                                 cluster_variable = NULL,
                                 type = "HC1",
                                 leverage = NULL) {
  type <- match.arg(type, c("HC0", "HC1", "HC3"))
  sc <- as.matrix(scores)
  J_j <- as.matrix(J)
  p <- ncol(sc)

  # Cluster aggregation: rowsum scores to cluster level
  clustered <- !is.null(cluster_variable) &&
    !identical(seq_len(nrow(sc)),
               as.integer(cluster_variable))
  if (clustered) {
    sc <- rowsum(sc, cluster_variable)
  }#IF

  n_eff <- nrow(sc)

  if (type == "HC3") {
    h <- leverage
    if (clustered) {
      h <- as.vector(tapply(h, cluster_variable, sum))
    }#IF
    sc <- sc / (1 - h)
    meat <- crossprod(sc) / n_eff
    J_inv <- solve(J_j)
    V <- J_inv %*% meat %*% t(J_inv) / n_eff
  } else if (type == "HC1") {
    meat <- crossprod(sc) / n_eff
    J_inv <- solve(J_j)
    V <- J_inv %*% meat %*% t(J_inv) *
      n_eff / (n_eff - p) / n_eff
  } else {
    # HC0
    meat <- crossprod(sc) / n_eff
    J_inv <- solve(J_j)
    V <- J_inv %*% meat %*% t(J_inv) / n_eff
  }#IFELSE

  V
}#COMPUTE_DDML_VARIANCE

compute_ddml_inference <- function(coefficients, scores, J,
                                  coef_names = NULL,
                                  ensemble_type,
                                  cluster_variable = NULL,
                                  type = "HC1",
                                  leverage_list = NULL) {
  nensb <- length(ensemble_type)
  p <- nrow(coefficients)

  inf_results <- array(0, dim = c(p, 4, nensb))

  for (j in seq_len(nensb)) {
    theta_j <- coefficients[, j]
    h <- if (!is.null(leverage_list)) leverage_list[[j]]

    V <- compute_ddml_variance(scores[[j]], J[[j]],
                              cluster_variable,
                              type = type,
                              leverage = h)
    se <- sqrt(diag(V))
    t_val <- theta_j / se
    p_val <- 2 * stats::pnorm(abs(t_val),
                               lower.tail = FALSE)

    inf_results[, 1, j] <- theta_j
    inf_results[, 2, j] <- se
    inf_results[, 3, j] <- t_val
    inf_results[, 4, j] <- p_val
  }#FOR

  dimnames(inf_results) <- list(
    coef_names,
    c("Estimate", "Std. Error", "t value", "Pr(>|t|)"),
    ensemble_type
  )
  inf_results
}#COMPUTE_DDML_INFERENCE
